add desired replication factor option
SiftScience/kafka-assigner pull request #4
Opened 2016-11-03 16:01 UTC by klorand

for situation in which you want to increase replication factor on a topic, besides moving partitions amond nodes

2016-11-03 16:32 UTC, kanakb requested changes

2016-11-03 16:32 UTC, kanakb commented on src/main/java/siftscience/kafka/tools/KafkaTopicAssigner.java
> +            } else if (desiredReplicationFactor<0) {
style nit: please add spaces on either side of the operator, i.e.
```java
} else if (desiredReplicationFactor < 0) {
```

2016-11-03 16:35 UTC, kanakb commented
Thanks for the contribution!

2016-11-03 16:47 UTC, kanakb approved these changes

2016-11-03 16:47 UTC, merged

2018-12-17 19:21 UTC, glasser commented
This change (and this project in general) is very helpful. Would you consider uploading a new tarball release?

2018-12-18 23:29 UTC, stalaie commented
@glasser, as @kanakb mentioned, thanks for your contribution. Working with the team here to address your question above. Stay tuned!

2018-12-18 23:40 UTC, glasser commented
Cool! FWIW I found #6 to be necessary as well.

It's hard for me to believe that this isn't just how kafka-reassign-partitions.sh works by default!

2018-12-19 22:53 UTC, ekoontz commented
Hi @glasser, thanks for your interest in kafka-assigner! I have created a new release 1.1, which includes this PR.
-Eugene

2018-12-19 22:53 UTC, ekoontz commented
I will also release a 1.2 which includes #6.